[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d58401ad770c603c4fee0477002c75899da785fd"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "e90ebbd7f5d73ec7207ba98e7e6d48881169ec9507e03ee8aac86964e49b44f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.aarch64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02805897e9f37e49939eaab1280b921de00d3052"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "1788276cfbc206331fe1aca27400b120577c9a5621acc220f0977de45e977be5"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.aarch64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
git-tree-sha1 = "6b647a03f18daf08bfb194d6af38cdd4eeb1c79b"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "3a3745c48be06d319fc7351406ca02813fe7839fabf9dfc6703d71d1170ee909"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.aarch64-unknown-freebsd.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e593b98051b58721ae10b1b53feaaf09f97821a"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "cd42795e0c19bc751de32bf8a32bbd9dbf2a80e38523a5f28e682aa779073ce4"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "869b6526b942149a24bb14a4ec25f3738d9f8526"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "ca3c4a852b68315e99a44ed65bb99567a423ee31b96beb5497c871888e65da2a"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6941183d42f099bd116222a493e75132be62c56a"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "6503097c43416909c0368c6408831b216c80a391fee36386efde62963bcbcd96"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f666bf9d64e957a31975513a3c6ac7dba5d3b5da"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "23bf3bdf65c3364e94164cb2977cbc0cfcbc622331f512b4fedadf23973741ec"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "557a45f5f9dc76b2cdeff46ad812764c0de4ac2e"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "6d2fc61c4fc64f3d603026de8e0d5cf88a214a766647fc9de82c7badf360adc8"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.i686-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c45935b6414a3a298d230314ab69c4ce1568bd6"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "ff059c796cd2c88a4694fbf2bcf20e33a1fe414537544eac8b23da66fca5ae6f"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.i686-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32638180993f4fc7767007980c665bf8407e895a"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "9f09684fa988a6a3fb1e62bf71dcc6faaa3b49ed3ecd168903626a95ec8ef6ea"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dadadcf1130fff242ba858705c7d9f3606f8925"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "d8db7346d02c2da3b8e56633889b1c1e6162b82916a5c0f164c81b5829d1a044"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.riscv64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b15e810d3644caf6cbe687182ac0d6fccd6154a7"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "bcd32ce39208d95bf6857193990f98ab496e8a474a56a4f9f0f5c587f7d1c32c"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.x86_64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b827c7941f80854bc4dcfd45ca4b2547a774efe4"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "664435d8dfe628bb4c83d0a572aadd7992c20e5a1f45bf7e944f099c280aa544"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.x86_64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
git-tree-sha1 = "85e5428ba9ebb29ea33ed7c66e86ac0fdf978368"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "8e2f89322b8c154e9b153a9ca480fe0bba81e529444318d73487decd07059497"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.73.0+0/aws_lc.v1.73.0.x86_64-unknown-freebsd.tar.gz"
