[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84d22dd443c4600f91942b02ba1ddee31bb419be"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "92180df43ed10004a5d6d8b727d6b4b40d81936c29d5120c23f2ee0b729d9866"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.aarch64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b232766d5066284e622843d62d140781ac3463b"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "153a25a800148e6ce32280938d514d1d095c600afa4024c534cef6c2b8c01b31"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.aarch64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
git-tree-sha1 = "16787beaaa266d8f0065d9cb16ebfe6159af9b1d"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "65ec3a5bfb77a5cc360806fdf53aa2708ed242c58494d762503d80842eee5b35"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.aarch64-unknown-freebsd.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e33e1101fce0dca37757827c7b0f77e8628cb60"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "6f9e9c08731e80c4b3f6d8285fd69e5541dc9d565895b4d40a692af350ca3e57"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9df1d9238e5551a6f9f502c018cb6bc918d647c"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "b10e11a1f007dde83721636c74cf7dd5d2e8b1097631bc06cb3417c557d47bc2"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb2fd08acd51f358221685e1b76efa764b690518"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "d98cce411b30dc186f11ede72d362847c4f6592beea32d418d4bff8c23546beb"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "602e49a3c9007f4f775159a7b0f086096ab120d7"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "721a753bbd974e2f5e4288b84b2d029e1d0c1cf46c08516250f619226a7d4595"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f37594dc592c538fb7a725b87874be6bec13badb"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "e346c87e4f8c763fa785bdbf9527f29b2f683694f3d150123b6acc34b889e7d0"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.i686-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "916f6aac74040ec6affad405c5f818f1d6324c93"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "0e21b6daf94427a332bf433a0552b750c4a3dccde19307978ffd9547aa37e154"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.i686-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "403ffdac81e841ceda98cd3b3d9c699c810250d9"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "f31be0e6998e6c4cd228088c89326978c466aa99bbffd22c559285bc1a3ce0f0"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c34b534160a804b94831667a0715be17cbfc02f"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "a7751863476967c1e046c503919f9066c85ca49ab4b9298151a00b814c580e5a"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.riscv64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f1dccb81f962b02a3c06f643e4fe623b8d4046c"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "bf556c15e6a39ebbbed1c5bcc25e377b87e626ae1b552337c4dc3899c289c0d2"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.x86_64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efa2841ab777088bcd850b128d0c23cd79213b7d"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "069a9d8d0ac4e2e933b56ad4c3fb64949c1b12c7c0c2364e83cb43753effc1fa"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.x86_64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
git-tree-sha1 = "6f1c4aabca8f42aaa6103e442591cfb0286f63d4"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "7d9e07e08f00c0dd08f0307d37e5fe2a06e01fdb4e50c8841690e5ed4061ac16"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.72.0+0/aws_lc.v1.72.0.x86_64-unknown-freebsd.tar.gz"
