# Autogenerated wrapper script for aws_lc_jll for aarch64-unknown-freebsd
export libcrypto, libssl

JLLWrappers.@generate_wrapper_header("aws_lc")
JLLWrappers.@declare_file_product(libcrypto)
JLLWrappers.@declare_file_product(libssl)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libcrypto,
        "lib/libcrypto.a",
    )

    JLLWrappers.@init_file_product(
        libssl,
        "lib/libssl.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
